dartagnan/menu/urls.py
from django.conf.urls import patterns, url
from dartagnan.menu import views


urlpatterns = patterns('',
    url(r'^$', views.menu, name='menu'),
    url(r'^category/(?P<category_name>.[-\w]+)', views.category, name='category'),
    url(r'^about$', views.about_us, name='about_us'),
    url(r'^locations$', views.locations, name='locations')
)

dartagnan/urls.py
from django.contrib import admin
from django.conf.urls import patterns, include, url
from dartagnan import views
from django.conf import settings
from django.conf.urls.static import static

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

        # Examples:
        # url(r'^$', 'dartagnan.views.home', name='home'),
        # url(r'^dartagnan/', include('dartagnan.foo.urls')),

        # Uncomment the admin/doc line below to enable admin documentation:
        url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

        # Uncomment the next line to enable the admin:
        url(r'^admin/', include(admin.site.urls)),
        url(r'^menu/', include('dartagnan.menu.urls')),
        url(r'^$', views.index, name='index')
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dartagnan/menu/models.py
from django.db import models
from autoslug import AutoSlugField


class Category(models.Model):
    class Meta:
        verbose_name_plural = "categories"

    title = models.CharField(max_length=100)
    slug = AutoSlugField(populate_from='title', default='')

    def __unicode__(self):
        return self.title


class MenuItem(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=600)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    category = models.ForeignKey(Category)
    isOnSale = models.BooleanField(default=False)
    salePrice = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    hidden = models.BooleanField(default=False)

    def __unicode__(self):
        return self.name


class RestaurantInfo(models.Model):
    name = models.CharField(max_length=100)
    aboutUs = models.TextField(max_length=10000)
    introBlurb = models.TextField(max_length=2000)
    founded = models.DateField()

    def __unicode__(self):
        return self.name


class Location(models.Model):

    streetAddress = models.CharField(max_length=100)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=2)
    zipCode = models.CharField(max_length=10)

    monday_opens_at = models.TimeField(null=True, blank=True)
    monday_closes_at = models.TimeField(null=True, blank=True)

    tuesday_opens_at = models.TimeField(null=True, blank=True)
    tuesday_closes_at = models.TimeField(null=True, blank=True)

    wednesday_opens_at = models.TimeField(null=True, blank=True)
    wednesday_closes_at = models.TimeField(null=True, blank=True)

    thursday_opens_at = models.TimeField(null=True, blank=True)
    thursday_closes_at = models.TimeField(null=True, blank=True)

    friday_opens_at = models.TimeField(null=True, blank=True)
    friday_closes_at = models.TimeField(null=True, blank=True)

    saturday_opens_at = models.TimeField(null=True, blank=True)
    saturday_closes_at = models.TimeField(null=True, blank=True)

    sunday_opens_at = models.TimeField(null=True, blank=True)
    sunday_closes_at = models.TimeField(null=True, blank=True)

    def is_open_at(self, day_to_check, time_of_day):

        hours_for_today = self.openDays.first(name=day_to_check).hours

        return hours_for_today.open <= time_of_day <= hours_for_today.closed

    def __unicode__(self):
        return self.streetAddress + ' ' + self.city + ', ' + self.state + ' ' + self.zipCode

dartagnan/menu/views.py
from django.http import HttpResponse
from dartagnan.menu.models import Category, RestaurantInfo, Location
from dartagnan.menu.helpers import get_context
from django.template import RequestContext, loader


def menu(request):
    rest_info = RestaurantInfo.objects.first()
    template = loader.get_template('menu.html')
    categories = Category.objects.all()
    context = get_context(request, {
        'restaurant_name': rest_info.name,
        'rest_info': rest_info,
        'categories': categories
    })
    return HttpResponse(template.render(context))

def category(request, category_name):
    selected_category = Category.objects.get(slug=category_name)
    template = loader.get_template('category.html')
    context = get_context(request, {
        'category': selected_category
    })

    return HttpResponse(template.render(context))


def about_us(request):
    about_us = RestaurantInfo.objects.first()
    template = loader.get_template('aboutus.html')
    context = get_context(request, {
        'about_us': about_us
    })

    return HttpResponse(template.render(context))


def locations(request):
    template = loader.get_template('locations.html')
    context = get_context(request, {
    })

    return HttpResponse(template.render(context))

dartagnan/views.py
from django.http import HttpResponse
from django.template import loader
from dartagnan.menu.models import RestaurantInfo
from dartagnan.menu.models import Location
from dartagnan.menu.helpers import get_context


def index(request):
    locations = Location.objects.all()
    template = loader.get_template('index.html')
    context = get_context(request, {
        'locations': locations,
        'blurb':  RestaurantInfo.objects.first().introBlurb
    })
    return HttpResponse(template.render(context))

dartagnan/templates/aboutus.html
{% extends "base.html" %}

{% block nav_bar %}
     <li class="active"><a href="about">About Us</a></li>
    <li><a href="./">Menu</a></li>
    <li><a href="locations">Locations</a></li>
{% endblock %}

{% block main_body %}

<div class="about_us well">
    <h1>About Us</h1>
    <h2>{{ rest_name }} - founded {{ founded }}</h2>
    {{ about_us.aboutUs|linebreaks}}
</div>

{% endblock %}

dartagnan/templates/base.html
<!DOCTYPE html>
<html>
    <head lang="en">
        <meta charset="UTF-8">
        <title>{{ rest_name }}</title>
        <link href='http://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Nunito' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
        {% load static from staticfiles %}
        <link href="{% static 'basestyle.css' %}" rel="stylesheet" type="text/css">
    </head>
<body role="document">
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">{{ rest_name }}</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            {% block nav_bar %}
            {% endblock %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
    <div class="container main" role="main">
        <div class="jumbotron">
            <h1>{{ rest_name }}</h1>
        </div>
     {% block main_body %}
      {% endblock %}
    </div>
</body>
</html>

dartagnan/templates/category.html
{% extends "base.html" %}

{% block nav_bar %}
     <li><a href="../about">About Us</a></li>
     <li><a href="../../">Menu</a></li>
     <li><a href="../locations">Locations</a></li>
{% endblock %}

{% block main_body %}
<div class="well">
{{ category }}
<ul class="well">
{% for item in category.menuitem_set.all %}
    <li>{{ item }}</li>
{% endfor %}
</ul>
</div>
{% endblock %}

dartagnan/templates/index.html
{% extends "base.html" %}

{% block nav_bar %}
     <li><a href="menu/about">About Us</a></li>
     <li><a href="menu">Menu</a></li>
     <li><a href="menu/locations">Locations</a></li>
{% endblock %}

{% block main_body %}

<ul class="well">
    {{ blurb }}
   {% if locations|length > 0 %}
    <h2>Visit us at one of our {{ locations|length }} convenient locations</h2>
    {% else %}
       <h2>Visit Us</h2>
    {% endif %}
 {% for location in locations %}
    {% if forloop.first or forloop.counter|add:"-1"|divisibleby:"3" %}
      <div class="row">
    {% endif %}

        <div class="col-md-4">
        <h2>{{ location.city }}, {{ location.state }}</h2>
     <iframe
      width="300"
      height="300"
      frameborder="0" style="border:0"
      src="https://www.google.com/maps/embed/v1/place?key=AIzaSyBZZDDXxSgOkfy6afmagV28dNfyXuXX5-E&q={{ location }}">
    </iframe>
        </div>
    {% if forloop.last or forloop.counter|divisibleby:"3"  %}
       </div>
    {% endif %}
 {% endfor %}
</ul>
{% endblock %}

dartagnan/templates/locations.html
{% extends "base.html" %}

{% block nav_bar %}
    <li><a href="about">About Us</a></li>
    <li><a href="./">Menu</a></li>
    <li class="active"><a href="locations">Locations</a></li>
{% endblock %}

{% block main_body %}
{{ category }}
{% endblock %}<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>

</body>
</html>

dartagnan/templates/menu.html
{% extends "base.html" %}

{% block nav_bar %}
     <li><a href=" about">About Us</a></li>
     <li class="active"><a href="#">Menu</a></li>
     <li><a href="locations">Locations</a></li>
{% endblock %}

{% block main_body %}
<ul class="well">
    {% for category in categories %}
    <li>
    <a href="/menu/category/{{ category.slug }}">{{ category.title }}</a>

    </li>
    {% endfor %}
</ul>
{% endblock %}